// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqiigtwdaqcqpqtnlelh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxaWlndHdkYXFjcXBxdG5sZWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMDMxODAsImV4cCI6MjA0OTU3OTE4MH0.ijX2T2hK5wDe7wGeRRG2aMkENd0z1WBvKXu2yejIiRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);